var featureSet = [{min: 4.6,
            max: 15.9,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'fixed acidity',
            unit:  'ml',
            initialValue: 7.4
        },
        {min: 0.12,
            max: 1.58,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'volatile acidity' ,
            unit:  'ml',
            initialValue: 0.7
        },
        {min: 0,
            max: 1,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'citric acid',
            unit:  'ml',
            initialValue: 0.03
        },
        {min: 0.9,
            max: 15.5,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'residual sugar',
            unit:  'ml',
            initialValue: 1.9
        },
        {min: 0.012,
            max: 0.611,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'chlorides',
            unit:  '%',
            initialValue: 0.076
        },
        {min: 1,
            max: 72,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'free sulfur dioxide',
            unit:  'ml',
            initialValue: 11
        },
        {min: 6,
            max: 1,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'total sulfur dioxide',
            unit:  'ml',
            initialValue: 34
        },
        {min: 0.99007,
            max: 289,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'density',
            unit:  'ml',
            initialValue: 0.9978
        },
        {min: 2.74,
            max: 1.00369,
            step: 4.01,
            name: 'alchohol' ,
            friendlyName: 'pH',
            unit:  'ml',
            initialValue: 3.51
        },
        {min: 0.33,
            max:2,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'sulphates',
            unit:  'ml',
            initialValue: 0.56
        },
        {min: 8.4,
            max:21,
            step: 0.0001,
            name: 'alchohol' ,
            friendlyName: 'alcohol',
            unit:  '%',
            initialValue: 9.4
        }]